[workspace]
members = [
  "acmicpc-1007",
  "acmicpc-1014",
  "acmicpc-1016",
  "acmicpc-1017",
  "acmicpc-1018",
  "acmicpc-1330",
  "acmicpc-2562",
  "acmicpc-2884",
  "acmicpc-3052",
  "leetcode-0001",
]